-- begin SIMPLEVALIDATION_CARGO_BAY
create unique index IDX_SIMPLEVALIDATION_CARGO_BAY_UNIQ_BAY_NUMBER on SIMPLEVALIDATION_CARGO_BAY (BAY_NUMBER) ^
create unique index IDX_SIMPLEVALIDATION_CARGO_BAY_UNIQ_NAME on SIMPLEVALIDATION_CARGO_BAY (NAME) ^
-- end SIMPLEVALIDATION_CARGO_BAY
