alter table ORDERMAN_CUSTOMER add constraint FK_ORDERMAN_CUSTOMER_LOGO_IMAGE foreign key (LOGO_IMAGE_ID) references SYS_FILE(ID);
create unique index IDX_ORDERMAN_CUSTOMER_UNIQ_EMAIL on ORDERMAN_CUSTOMER (EMAIL) ;
create index IDX_ORDERMAN_CUSTOMER_LOGO_IMAGE on ORDERMAN_CUSTOMER (LOGO_IMAGE_ID);
