alter table ORDERMAN_STOCK add constraint FK_ORDERMAN_STOCK_PRODUCT foreign key (PRODUCT_ID) references ORDERMAN_PRODUCT(ID);
create unique index IDX_ORDERMAN_STOCK_UNIQ_PRODUCT_ID on ORDERMAN_STOCK (PRODUCT_ID) ;
create index IDX_ORDERMAN_STOCK_PRODUCT on ORDERMAN_STOCK (PRODUCT_ID);
