alter table ORDERMAN_ORDER add constraint FK_ORDERMAN_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references ORDERMAN_CUSTOMER(ID);
alter table ORDERMAN_ORDER add constraint FK_ORDERMAN_ORDER_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID);
create index IDX_ORDERMAN_ORDER_CUSTOMER on ORDERMAN_ORDER (CUSTOMER_ID);
create index IDX_ORDERMAN_ORDER_MANAGER on ORDERMAN_ORDER (MANAGER_ID);
