-- begin ORDERMANAGEMENT_CUSTOMER
alter table ORDERMANAGEMENT_CUSTOMER add constraint FK_ORDERMANAGEMENT_CUSTOMER_LOGO_IMAGE foreign key (LOGO_IMAGE_ID) references SYS_FILE(ID)^
create unique index IDX_ORDERMANAGEMENT_CUSTOMER_UNIQ_EMAIL on ORDERMANAGEMENT_CUSTOMER (EMAIL) ^
create index IDX_ORDERMANAGEMENT_CUSTOMER_LOGO_IMAGE on ORDERMANAGEMENT_CUSTOMER (LOGO_IMAGE_ID)^
-- end ORDERMANAGEMENT_CUSTOMER
-- begin ORDERMANAGEMENT_PRODUCT
create unique index IDX_ORDERMANAGEMENT_PRODUCT_UNQ on ORDERMANAGEMENT_PRODUCT (NAME, MEASURE) ^
-- end ORDERMANAGEMENT_PRODUCT
-- begin ORDERMANAGEMENT_STOCK
alter table ORDERMANAGEMENT_STOCK add constraint FK_ORDERMANAGEMENT_STOCK_PRODUCT foreign key (PRODUCT_ID) references ORDERMANAGEMENT_PRODUCT(ID)^
create index IDX_ORDERMANAGEMENT_STOCK_PRODUCT on ORDERMANAGEMENT_STOCK (PRODUCT_ID)^
-- end ORDERMANAGEMENT_STOCK
-- begin ORDERMANAGEMENT_ORDER_ITEM
alter table ORDERMANAGEMENT_ORDER_ITEM add constraint FK_ORDERMANAGEMENT_ORDER_ITEM_PRODUCT foreign key (PRODUCT_ID) references ORDERMANAGEMENT_PRODUCT(ID)^
alter table ORDERMANAGEMENT_ORDER_ITEM add constraint FK_ORDERMANAGEMENT_ORDER_ITEM_ORDER foreign key (ORDER_ID) references ORDERMANAGEMENT_ORDER(ID)^
create index IDX_ORDERMANAGEMENT_ORDER_ITEM_PRODUCT on ORDERMANAGEMENT_ORDER_ITEM (PRODUCT_ID)^
create index IDX_ORDERMANAGEMENT_ORDER_ITEM_ORDER on ORDERMANAGEMENT_ORDER_ITEM (ORDER_ID)^
-- end ORDERMANAGEMENT_ORDER_ITEM
-- begin ORDERMANAGEMENT_ORDER
alter table ORDERMANAGEMENT_ORDER add constraint FK_ORDERMANAGEMENT_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references ORDERMANAGEMENT_CUSTOMER(ID)^
alter table ORDERMANAGEMENT_ORDER add constraint FK_ORDERMANAGEMENT_ORDER_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
create index IDX_ORDERMANAGEMENT_ORDER_CUSTOMER on ORDERMANAGEMENT_ORDER (CUSTOMER_ID)^
create index IDX_ORDERMANAGEMENT_ORDER_MANAGER on ORDERMANAGEMENT_ORDER (MANAGER_ID)^
-- end ORDERMANAGEMENT_ORDER
