-- begin LISTENERSVALIDATION_PRINTER
create unique index IDX_LISTENERSVALIDATION_PRINTER_UNIQ_NAME on LISTENERSVALIDATION_PRINTER (NAME) ^
-- end LISTENERSVALIDATION_PRINTER
-- begin LISTENERSVALIDATION_PRINT_JOB
alter table LISTENERSVALIDATION_PRINT_JOB add constraint FK_LISTENERSVALIDATION_PRINT_JOB_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table LISTENERSVALIDATION_PRINT_JOB add constraint FK_LISTENERSVALIDATION_PRINT_JOB_PRINTER foreign key (PRINTER_ID) references LISTENERSVALIDATION_PRINTER(ID)^
create index IDX_LISTENERSVALIDATION_PRINT_JOB_FILE on LISTENERSVALIDATION_PRINT_JOB (FILE_ID)^
create index IDX_LISTENERSVALIDATION_PRINT_JOB_PRINTER on LISTENERSVALIDATION_PRINT_JOB (PRINTER_ID)^
-- end LISTENERSVALIDATION_PRINT_JOB
