-- begin CONTROLLERSVALIDATION_VENDOR
alter table CONTROLLERSVALIDATION_VENDOR add constraint FK_CONTROLLERSVALIDATION_VENDOR_LOGO foreign key (LOGO_ID) references SYS_FILE(ID)^
create index IDX_CONTROLLERSVALIDATION_VENDOR_LOGO on CONTROLLERSVALIDATION_VENDOR (LOGO_ID)^
-- end CONTROLLERSVALIDATION_VENDOR
-- begin CONTROLLERSVALIDATION_PRODUCT
alter table CONTROLLERSVALIDATION_PRODUCT add constraint FK_CONTROLLERSVALIDATION_PRODUCT_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
alter table CONTROLLERSVALIDATION_PRODUCT add constraint FK_CONTROLLERSVALIDATION_PRODUCT_VENDOR foreign key (VENDOR_ID) references CONTROLLERSVALIDATION_VENDOR(ID)^
create index IDX_CONTROLLERSVALIDATION_PRODUCT_IMAGE on CONTROLLERSVALIDATION_PRODUCT (IMAGE_ID)^
create index IDX_CONTROLLERSVALIDATION_PRODUCT_VENDOR on CONTROLLERSVALIDATION_PRODUCT (VENDOR_ID)^
-- end CONTROLLERSVALIDATION_PRODUCT
